# Generated by Django 5.1.6 on 2025-03-01 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='episodioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.CharField(max_length=10, unique=True)),
                ('nome_episodio', models.CharField(max_length=200)),
                ('numero_temporda_episodio', models.CharField(max_length=50)),
                ('data_lancamento_episodio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='reviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviwEpisodios.episodiomodel')),
            ],
        ),
    ]
