# Generated by Django 5.1.6 on 2025-03-01 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviwEpisodios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('data_lancamento', models.DateField()),
                ('codigo_episodio', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='episodio',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviwEpisodios.episodio')),
            ],
        ),
        migrations.DeleteModel(
            name='episodioModel',
        ),
        migrations.DeleteModel(
            name='reviewModel',
        ),
    ]
